// FILE GENERATED BY FLUTTERFIRE — replace placeholder values with your own.
// Run: flutterfire configure
// Or copy values manually from the Firebase Console.
//
// Current values point at `affinity-dev-local` (Jenith's dev project).
// Swap to production values at integration time — see
// docs/STORE_SUBMISSION.md "Secrets handed off to the store runtime".
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux — '
          'reconfigure by running: flutterfire configure',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── affinity-dev-local (Jenith dev) ─────────────────────────────────────
  // Source: google-services.json (Android) + Firebase Console values.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsF2BJljP4nKJHg2AlNYvoo-GkrUhvt9M',
    appId: '1:969381919875:android:4e77c055c9e20a26a52fb6',
    messagingSenderId: '969381919875',
    projectId: 'affinity-dev-local',
    storageBucket: 'affinity-dev-local.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsF2BJljP4nKJHg2AlNYvoo-GkrUhvt9M',
    appId: '1:969381919875:ios:PLACEHOLDER_REGISTER_IOS_IN_FIREBASE',
    messagingSenderId: '969381919875',
    projectId: 'affinity-dev-local',
    storageBucket: 'affinity-dev-local.firebasestorage.app',
    iosBundleId: 'com.affinitysocialclub.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsF2BJljP4nKJHg2AlNYvoo-GkrUhvt9M',
    appId: '1:969381919875:web:PLACEHOLDER_REGISTER_WEB_IN_FIREBASE',
    messagingSenderId: '969381919875',
    projectId: 'affinity-dev-local',
    authDomain: 'affinity-dev-local.firebaseapp.com',
    storageBucket: 'affinity-dev-local.firebasestorage.app',
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions windows = web;
}
