// FILE GENERATED BY FLUTTERFIRE — replace placeholder values with your own.
// Run: flutterfire configure
// Or copy values manually from the Firebase Console.
//
// Points at `affinity-dating-app-cf807` — the client's official project.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux — '
          'reconfigure by running: flutterfire configure',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── affinity-dating-app-cf807 (client production) ──────────────────────
  // Source: google-services.json (Android) + Firebase Console values.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ21D3vILE78y4gT8dmsz6SexHd_wcuZw',
    appId: '1:156489398688:android:77e8ecdd2961c6ae984cc5',
    messagingSenderId: '156489398688',
    projectId: 'affinity-dating-app-cf807',
    storageBucket: 'affinity-dating-app-cf807.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ21D3vILE78y4gT8dmsz6SexHd_wcuZw',
    appId: '1:156489398688:ios:PLACEHOLDER_REGISTER_IOS_IN_FIREBASE',
    messagingSenderId: '156489398688',
    projectId: 'affinity-dating-app-cf807',
    storageBucket: 'affinity-dating-app-cf807.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ21D3vILE78y4gT8dmsz6SexHd_wcuZw',
    appId: '1:156489398688:web:PLACEHOLDER_REGISTER_WEB_IN_FIREBASE',
    messagingSenderId: '156489398688',
    projectId: 'affinity-dating-app-cf807',
    authDomain: 'affinity-dating-app-cf807.firebaseapp.com',
    storageBucket: 'affinity-dating-app-cf807.firebasestorage.app',
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions windows = web;
}
