# Step 3 of the Mac-free iOS code-signing flow:
#
#   1. CSR + private key generated by us via OpenSSL (one-shot)
#   2. Operator uploads the .csr to Apple Developer -&gt; downloads a .cer
#   3. This script combines the .cer + matching private key into a
#      .p12 that release-ipa.yml expects as IOS_DIST_CERT_P12_BASE64
#
# Usage:
#   pwsh -File scripts/build_ios_p12.ps1 `
#     -CerPath "C:\Users\Amibong\Downloads\distribution.cer" `
#     [-KeyPath "C:\Users\Amibong\affinity-ios-dist.key"] `
#     [-OutPath "C:\Users\Amibong\affinity-ios-dist.p12"]

param(
    [Parameter(Mandatory=$true)]
    [string]$CerPath,

    [string]$KeyPath = "$HOME\affinity-ios-dist.key",

    [string]$OutPath = "$HOME\affinity-ios-dist.p12"
)

$openssl = "C:\Program Files\Git\usr\bin\openssl.exe"

foreach ($p in @($CerPath, $KeyPath, $openssl)) {
    if (-not (Test-Path $p)) {
        Write-Host "::: Required file does not exist: $p" -ForegroundColor Red
        exit 1
    }
}

if (Test-Path $OutPath) {
    Write-Host "::: A .p12 already exists at $OutPath -- delete manually to regenerate." -ForegroundColor Yellow
    exit 1
}

# Strong random password -- same shape as the keystore generator.
$bytes = New-Object byte[] 16
[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
$P12Password = -join ($bytes | ForEach-Object { '{0:x2}' -f $_ })

# Apple's .cer is DER-encoded; OpenSSL wants PEM for the pkcs12 -in flag.
$pemPath = "$env:TEMP\affinity-dist-$([guid]::NewGuid()).pem"
Write-Host "::: Converting Apple's DER .cer to PEM ..." -ForegroundColor Cyan
& $openssl x509 -in $CerPath -inform DER -out $pemPath -outform PEM
if ($LASTEXITCODE -ne 0) {
    Write-Host "::: openssl x509 conversion failed." -ForegroundColor Red
    exit 1
}

Write-Host "::: Bundling private key + certificate into .p12 ..." -ForegroundColor Cyan
& $openssl pkcs12 -export `
    -inkey $KeyPath `
    -in $pemPath `
    -out $OutPath `
    -name "Affinity Apple Distribution" `
    -passout "pass:$P12Password"
Remove-Item $pemPath -ErrorAction SilentlyContinue
if ($LASTEXITCODE -ne 0) {
    Write-Host "::: openssl pkcs12 export failed." -ForegroundColor Red
    exit 1
}

$P12Base64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($OutPath))

Write-Host ""
Write-Host "::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::" -ForegroundColor Green
Write-Host "::: .p12 created at $OutPath" -ForegroundColor Green
Write-Host "::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::" -ForegroundColor Green
Write-Host ""
Write-Host "IOS_DIST_CERT_P12_BASE64" -ForegroundColor Cyan
Write-Host $P12Base64
Write-Host ""
Write-Host "IOS_DIST_CERT_PASSWORD" -ForegroundColor Cyan
Write-Host $P12Password
Write-Host ""
Write-Host "IOS_TEAM_ID" -ForegroundColor Cyan
Write-Host "VTP3W3Y6FA"
Write-Host ""
Write-Host "::: You still need IOS_PROVISIONING_PROFILE_BASE64 -- once you" -ForegroundColor Cyan
Write-Host "::: download the .mobileprovision from Apple Developer (Phase 2c)," -ForegroundColor Cyan
Write-Host "::: run: pwsh -File scripts/prep_ios_release_secrets.ps1 ..." -ForegroundColor Cyan
